In [ ]:
import numpy as np#随机数生成
array1=np.random.uniform(low=0,high=5,size=10)#5 个 [5.0, 10.0) 的随机数,均匀分布
array2=np.random.rand(10)#快速生成随机数
array3=np.random.randn(10)#正态分布
array4=np.random.randint(0,9)#离散分布
array1,array2 ,array3, array4

(array([1.95381615, 2.10686682, 1.85244682, 1.86663136, 4.93524321,
        0.63878898, 0.76438402, 4.3831204 , 2.04540057, 3.39472896]),
 array([0.57956273, 0.80421356, 0.39170386, 0.74817834, 0.09124081,
        0.63602654, 0.58722288, 0.3452939 , 0.53972796, 0.49270738]),
 array([-1.16600987,  0.71316935, -1.52760635, -0.80628975, -0.09518218,
         1.3530078 ,  2.45620657,  1.73802227,  0.2732865 , -0.64647366]),
 2)

In [ ]:
import numpy as np#算术处理
data=[1,2,3,4,5]
avg=np.mean(data)#计算平均值
a=max(data)#计算最大值
b=sum(data)#求和
avg,a,b

(3.0, 5, 15)