In [ ]:
import numpy as np#np对象的创建
a=[1,2,3]
a=np.array=(a)
b=np.arange(3)#生成等间隔的
c=np.empty(3)#生成未初始化的
d=np.zeros(3)#生成用0填充的
e=np.ones(3)#生成用1填充的
"""
np.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)
dtype:数据类型
ndmin:最小维度
""" 
"""
numpy.arange(start, stop, step, dtype)
start:默认为0
stop:终止范围不包括
step:步长默认为1
dtype:数据类型
"""
a,b,c,d,e 

([1, 2, 3],
 array([0, 1, 2]),
 array([ 6.95245671e-310,  1.02268151e-311, -0.00000000e+000]),
 array([0., 0., 0.]),
 array([1., 1., 1.]))

In [ ]:
import numpy as np
a= np.array([[1,2,3],[4,5,6]])  
print(a.shape)#数组维度
a= np.array([[1,2,3],[4,5,6]]) 
a.shape=(3,2)#调整维度


(2, 3)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [1]:
import numpy as np#随机数生成
array1=np.random.uniform(low=0,high=5,size=10)#5 个 [5.0, 10.0) 的随机数,均匀分布
array2=np.random.rand(10)#快速生成随机数
array3=np.random.randn(10)#正态分布
array4=np.random.randint(0,9)#离散分布
array1,array2 ,array3, array4

(array([0.42815619, 1.13786456, 0.98588407, 3.32445911, 2.43683337,
        4.82372069, 2.26053595, 0.48909483, 2.28291526, 4.4188979 ]),
 array([0.96406907, 0.93358533, 0.47988718, 0.02940523, 0.40138002,
        0.22636351, 0.84254487, 0.35879508, 0.6122585 , 0.84519227]),
 array([-1.22456219,  0.39259563,  0.0503079 , -0.42175888,  0.35259076,
        -1.42330247, -0.95946237,  0.02303746, -0.44394152, -0.95866591]),
 3)

In [ ]:
import numpy as np#算术处理
data=[1,2,3,4,5]
avg=np.mean(data)#计算平均值
a=max(data)#计算最大值
b=sum(data)#求和
avg,a,b

(3.0, 5, 15)